version: '3'
services:
  app:
    container_name: offpro
    restart: always
    build: 
      context: .
    ports:
      - '80:5000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      -  JWT_SECRET=BeBNuHjmsXNoUGjekeLIztJi2ykAIR8aefOv7FIyURUb4m6I2dRUQ53uT71ohGk1
      -  TWILIO_ACCOUNT_SID=ACcda791381d569747b33c5568bedfd11a
      -  TWILIO_AUTH_TOKEN=2b07209d80c907243263a46a722d33ba
      -  TWILIO_SERVICE_ID=VAd5df8e634ec0fe9c775db69c99e45563
    volumes:
      - ./:/usr/app/src
      
  mongo:
    container_name: mongo
    volumes:
      - offproDb:/data/db
    image: mongo
    ports:
      - '27017:27017'
volumes:
  offproDb: